{{/*
Return spec of the persistent volume claim template.
{{ include "czertainly-lib.persistence.spec.template" ( dict "persistence" .Values.persistence "global" .Values.global.persistence) }}
*/}}
{{- define "czertainly-lib.persistence.spec.template" -}}
{{- $size := pluck "size" .Values.global.persistence .Values.persistence | compact | first -}}
{{- $accessModes := pluck "accessModes" .Values.global.persistence .Values.persistence | compact | first -}}
{{- $storageClassName := pluck "storageClassName" .Values.global.persistence .Values.persistence | compact | first -}}
{{- $selector := pluck "selector" .Values.global.persistence .Values.persistence | compact | first -}}
accessModes:
  {{- range $accessModes }}
  - {{ . | quote }}
  {{- end }}
resources:
  requests:
    storage: {{ $size | quote }}
{{- if $storageClassName }}
storageClassName: {{ $storageClassName }}
{{- end }}
{{- if $selector }}
selector: {{- $selector | toYaml | nindent 4 }}
{{- end -}}
{{- end -}}
