{{- define "czertainly-lib.trusted.certificates.secret.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-certificates
type: Opaque
data: {}
{{- end -}}

{{- define "czertainly-lib.trusted.certificates.secret" -}}
{{- include "czertainly-lib.util.merge" (append . "czertainly-lib.trusted.certificates.secret.tpl") -}}
{{- end -}}

{{- define "czertainly-lib.trusted.certificates.secret.local.tpl" -}}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-certificates-{{ .Chart.Name | lower }}
type: Opaque
data: {}
{{- end -}}

{{- define "czertainly-lib.trusted.certificates.secret.local" -}}
{{- include "czertainly-lib.util.merge" (append . "czertainly-lib.trusted.certificates.secret.local.tpl") -}}
{{- end -}}

{{- define "czertainly-lib.trusted.certificates.secret.global" -}}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-certificates
type: Opaque
data:
  ca.crt: {{ required "List of trusted certificates is required: .Values.global.trusted.certificates!" .Values.global.trusted.certificates | b64enc }}
{{- end -}}