apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  password: {{ pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
  username: {{ pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
kind: Secret
metadata:
  name: ejbca-ng-connector-secret