{{- $additionalPorts := (include "keycloak-internal.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak-internal-service
  labels:
    {{- include "keycloak-internal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: "TCP"
    - name: https-redirect
      port: 443
      targetPort: 8443
      protocol: "TCP"
    - name: http-redirect
      port: 80
      targetPort: 8080
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "keycloak-internal.selectorLabels" . | nindent 4 }}