apiVersion: v1
kind: Service
metadata:
  name: keycloak-internal-service-headless
  labels:
    {{- include "keycloak-internal.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: "TCP"
      targetPort: http
  selector:
    {{- include "keycloak-internal.selectorLabels" . | nindent 4 }}