apiVersion: v1
data:
  # if the global values are defined, use it, otherwise use local values
  connection-string: {{ include "czertainly-lib.util.format.netUrl" (list . ) | b64enc }}
kind: Secret
metadata:
  name: auth-secret