apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    {{- include "api-gateway-haproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
  selector:
    {{- include "api-gateway-haproxy.selectorLabels" . | nindent 4 }}