{{- $additionalPorts := (include "software-cryptography-provider.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  name: software-cryptography-provider-service
  labels:
    {{- include "software-cryptography-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "software-cryptography-provider.selectorLabels" . | nindent 4 }}
