{{- $additionalPorts := (include "ms-adcs-connector.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  name: ms-adcs-connector-service
  labels:
    {{- include "ms-adcs-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "ms-adcs-connector.selectorLabels" . | nindent 4 }}