{{- $username := pluck "username" .Values.global.database .Values.database | compact | first | b64enc | quote }}
{{- $password := pluck "password" .Values.global.database .Values.database | compact | first | b64enc | quote }}
apiVersion: v1
data:
  jdbcPassword: {{ $password }}
  jdbcUsername: {{ $username }}
kind: Secret
metadata:
  name: core-secret