apiVersion: v1
kind: ConfigMap
metadata:
  name: global-configmap
data:
  {{- include "czertainly-lib.api-gateway.kong.yaml" (dict "global" .Values.global "apiGateway" .Values.apiGateway) | indent 2 }}
  {{- include "czertainly-lib.messaging.configmap" (dict "global" .Values.global "messagingService" .Values.messagingService) | nindent 2 }}
