apiVersion: v1
kind: Secret
metadata:
  name: global-secret
stringData:
  {{- include "czertainly-lib.messaging.secrets" (dict "global" .Values.global "messagingService" .Values.messagingService "release" .Release) | indent 2 }}
