{{- $trusted := pluck "certificates" .Values.global.trusted .Values.trusted | compact | first | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: trusted-certificates
type: Opaque
data:
  ca.crt: {{ required "List of trusted certificates is required: .Values.trusted.certificates!" $trusted }}