{{- if not .Values.global.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: messaging-secret
stringData:
  {{- include "czertainly-lib.messaging.secrets" (dict "global" .Values.global "messagingService" .Values "release" .Release) | indent 2 }}
{{- end }}
