apiVersion: v1
kind: Service
metadata:
  name: messaging-service-headless
  labels:
    {{- include "messaging-rabbitmq.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: {{ .Values.service.headless.epmd.port }}
      protocol: "TCP"
      targetPort: {{ .Values.service.headless.epmd.port }}
    - name: cluster-rpc
      port: {{ .Values.service.headless.clusterRpc.port }}
      protocol: "TCP"
      targetPort: {{ .Values.service.headless.clusterRpc.port }}
  sessionAffinity: None
  selector:
    {{- include "messaging-rabbitmq.selectorLabels" . | nindent 4 }}