apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api-gateway-kong.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "api-gateway-kong.serviceAccountName" . }}
roleRef:
  kind: Role
  name: api-gateway-role
  apiGroup: rbac.authorization.k8s.io