apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-gateway-kong.serviceAccountName" . }}
  labels:
    {{- include "api-gateway-kong.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}