apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: czertainly-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "czertainly.serviceAccountName" . }}
roleRef:
  kind: Role
  name: czertainly-role
  apiGroup: rbac.authorization.k8s.io