apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: czertainly-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "get", "list", "delete", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "delete", "patch" ]