{{- if .Values.registerAdmin.enabled -}}
{{- if eq .Values.registerAdmin.source "external" -}}
apiVersion: v1
kind: Secret
metadata:
  name: admin-certificate-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid admin certificate is required: .Values.registerAdmin.admin.certificate!" .Values.registerAdmin.admin.certificate | b64enc }}
  tls.key: {{ required "A valid admin certificate is required: .Values.registerAdmin.admin.certificate!" .Values.registerAdmin.admin.certificate | b64enc }}
{{- end -}}
{{- end -}}