{{- if .Values.registerAdmin.enabled -}}
{{- if eq .Values.registerAdmin.source "generated" -}}
  {{- $certmanagerVer :=  split "." .Values.certManager.version -}}
  {{- if or (.Capabilities.APIVersions.Has "cert-manager.io/v1beta1") (and (gt (len $certmanagerVer._0) 0) (eq (int $certmanagerVer._0) 0) (ge (int $certmanagerVer._1) 16)) }}
apiVersion: cert-manager.io/v1beta1
  {{- else if or (.Capabilities.APIVersions.Has "cert-manager.io/v1alpha2") (and (gt (len $certmanagerVer._0) 0) (eq (int $certmanagerVer._0) 0) (ge (int $certmanagerVer._1) 11)) }}
apiVersion: cert-manager.io/v1alpha2
  {{- else if or (.Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1") (and (gt (len $certmanagerVer._0) 0) (eq (int $certmanagerVer._0) 0) (lt (int $certmanagerVer._1) 11)) }}
apiVersion: certmanager.k8s.io/v1alpha1
  {{- else }}
apiVersion: cert-manager.io/v1
  {{- end }}
kind: Certificate
metadata:
  name: admin-certificate
  labels:
    {{- include "czertainly.labels" . | nindent 4 }}
spec:
  secretName: admin-certificate-secret
  duration: 2160h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
  issuerRef:
    name: admin-ca-issuer
    kind: Issuer
  commonName: czertainly-administrator
{{- end -}}
{{- end -}}