apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: messaging-role-binding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "messaging-rabbitmq.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "messaging-rabbitmq.serviceAccountName" . }}
roleRef:
  kind: Role
  name: messaging-role
  apiGroup: rbac.authorization.k8s.io