apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "messaging-rabbitmq.serviceAccountName" . }}
  labels:
    {{- include "messaging-rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}