{{- $hostName := pluck "hostName" .Values.global .Values | compact | first }}
_format_version: '2.1'
_transform: true
services:
  - name: protocols
    host: {{ .Values.backend.core.service.name }}
    port: {{ .Values.backend.core.service.port }}
    protocol: http
    routes:
      - name: protocols_route
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}/v1/protocols
  - name: core
    host: {{ .Values.backend.core.service.name }}
    port: {{ .Values.backend.core.service.port }}
    protocol: http
    routes:
      - name: core_route-cert
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}
        headers:
          ssl-client-cert:
            - ~*(.*?)
        plugins:
          - name: request-transformer
            config:
              rename:
                headers:
                  - '{{ .Values.auth.header.cert.downstream }}:{{ .Values.auth.header.cert.upstream }}'
      {{- if or .Values.global.keycloak.enabled .Values.oidc.enabled }}
      - name: core_route-oidc
        strip_path: false
        preserve_host: true
        paths:
          - {{ .Values.backend.core.service.apiUrl}}
        plugins:
          - name: oidc
            config:
              {{- if .Values.global.keycloak.enabled }}
              client_secret: {{ .Values.global.keycloak.clientSecret }}
              client_id: kong
              unauth_action: 'deny'
              realm: CZERTAINLY
              discovery: >-
                https://{{ $hostName }}/kc/realms/CZERTAINLY/.well-known/openid-configuration
              {{- else if .Values.oidc.enabled }}
              client_secret: {{ .Values.oidc.client.secret }}
              client_id: {{ .Values.oidc.client.id }}
              unauth_action: 'deny'
              realm: {{ .Values.oidc.client.realm }}
              discovery: >-
                {{ .Values.oidc.client.discovery }}
              {{- end }}
          - name: request-transformer
            config:
              remove:
                headers:
                  - cookie
      {{- end }}
  - name: fe-administrator
    host: {{ .Values.backend.fe.service.name}}
    port: {{ .Values.backend.fe.service.port }}
    protocol: http
    routes:
      - name: fe-administrator_route-cert
        preserve_host: true
        strip_path: true
        paths:
          - {{ .Values.backend.fe.service.baseUrl}}
        headers:
          ssl-client-cert:
            - ~*(.*?)
        plugins:
          - name: request-transformer
            config:
              rename:
                headers:
                  - '{{ .Values.auth.header.cert.downstream }}:{{ .Values.auth.header.cert.upstream }}'
      {{- if or .Values.global.keycloak.enabled .Values.oidc.enabled }}
      - name: fe-administrator_route-oidc
        strip_path: true
        preserve_host: true
        paths:
          - {{ .Values.backend.fe.service.loginUrl}}
        plugins:
          - name: oidc
            config:
              {{- if .Values.global.keycloak.enabled }}
              client_secret: {{ .Values.global.keycloak.clientSecret }}
              client_id: kong
              realm: CZERTAINLY
              discovery: >-
                https://{{ $hostName }}/kc/realms/CZERTAINLY/.well-known/openid-configuration
              {{- else if .Values.oidc.enabled }}
              client_secret: {{ .Values.oidc.client.secret }}
              client_id: {{ .Values.oidc.client.id }}
              realm: {{ .Values.oidc.client.realm }}
              discovery: >-
                {{ .Values.oidc.client.discovery }}
              {{- end }}
          - name: response-transformer
            config:
              add:
                headers:
                  - cache-control:no-cache,no-store,max-age=0
          - name: post-function
            config:
              access:
                - |2
                    -- Get redirect query value
                    local redirect = kong.request.get_query_arg('redirect')

                    -- add validation of redirect path
                    -- should start with /$BASE_URL/

                    -- Redirect only if the redirect exists
                    if redirect then
                      kong.log.debug('Redirecting to: ' .. redirect)
                      return kong.response.exit(301, 'redirecting...', {['Location'] = redirect})
                    end
      - name: fe-administrator_route-logout
        strip_path: true
        preserve_host: true
        paths:
          - {{ .Values.backend.fe.service.logoutUrl}}
        plugins:
          - name: oidc
            config:
              {{- if .Values.global.keycloak.enabled }}
              client_secret: {{ .Values.global.keycloak.clientSecret }}
              client_id: kong
              realm: CZERTAINLY
              discovery: >-
                https://{{ $hostName }}/kc/realms/CZERTAINLY/.well-known/openid-configuration
              {{- else if .Values.oidc.enabled }}
              client_secret: {{ .Values.oidc.client.secret }}
              client_id: {{ .Values.oidc.client.id }}
              realm: {{ .Values.oidc.client.realm }}
              discovery: >-
                {{ .Values.oidc.client.discovery }}
              {{- end }}
              # null because the default value is '/' and we need to invoke endpoint from discovery, if discovery does not provide it, it should be defined here
              redirect_after_logout_uri: null
              redirect_after_logout_with_id_token_hint: 'yes'
              post_logout_redirect_uri: >-
                https://{{ $hostName }}{{ .Values.backend.fe.service.baseUrl}}/
      - name: fe-administrator_route
        strip_path: true
        preserve_host: true
        paths:
          - {{ .Values.backend.fe.service.baseUrl}}
      {{- end }}
  {{- if or .Values.global.keycloak.enabled }}
  - name: keycloak-internal-service
    host: keycloak-internal-service
    port: 8080
    routes:
      - name: keycloak
        strip_path: false
        preserve_host: true
        paths:
          - /kc
  {{- end }}
  {{- if or .Values.global.messaging.remoteAccess }}
  - name: messaging-service
    host: messaging-service
    port: 15672
    routes:
      - name: rabbitmq
        strip_path: true
        preserve_host: true
        paths:
          - /mq
  {{- end }}
  {{- if or .Values.global.utils.enabled }}
  - name: utils-service-service
    host: utils-service-service
    port: 8080
    routes:
      - name: v1-utils-route
        strip_path: true
        preserve_host: true
        paths:
          - /utils
  {{- end }}
{{- if .Values.cors.enabled }}
plugins:
  - name: cors
    config:
      origins: {{ toYaml .Values.cors.origins | nindent 8 }}
      credentials: true
      max_age: 3600
      exposed_headers: {{ toYaml .Values.cors.exposedHeaders | nindent 8 }}
      preflight_continue: false
{{- end }}