{{- $additionalPorts := (include "common-credential-provider.customization.ports" $) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common-credential-provider.labels" . | nindent 4 }}
  name: common-credential-provider-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: "TCP"
    {{- if $additionalPorts }}
      {{- $additionalPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "common-credential-provider.selectorLabels" . | nindent 4 }}
